// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUmv1rwXrXcRZFEG3tyjV6d0za-6_EHFA',
    appId: '1:973058756320:android:17327a30415442fc45ca85',
    messagingSenderId: '973058756320',
    projectId: 'shop-14eb2',
    storageBucket: 'shop-14eb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2NwTYCnEbMjUC8UuOe0yxxIzhYL5rZX4',
    appId: '1:973058756320:ios:9241329c4f08094645ca85',
    messagingSenderId: '973058756320',
    projectId: 'shop-14eb2',
    storageBucket: 'shop-14eb2.appspot.com',
    androidClientId: '973058756320-b0as6vsh1h3sch9m11rqusiihavque3a.apps.googleusercontent.com',
    iosClientId: '973058756320-q37kb6pji2clvhanc04lovg2q54596fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );
}
